### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by Jerry-Z07** [hanasa2023/nonebot-plugin-ba-tools#8]
py3.1.0
ubuntu 22.04
1 涩图功能无法指定数目
10-01 23:21:23 [SUCCESS] nonebot | OneBot V11 ***051 | [message.group.normal]: Message 1****381 from superuser@[群:37*****] '[at:qq=机器人] /ba涩图 2'
之后无任何输出
2 学生生日表无法获取
10-01 23:23:23 [SUCCESS] nonebot | OneBot V11 ***051 | [message.group.normal]: Message 8****36 from @[群:37*****] '[at:qq=] /ba学生生日表 9月'

```

10-01 23:23:23 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_ba_tools.get_student_birthday, lineno=31)
10-01 23:23:24 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_ba_tools.get_student_birthday, lineno=31) running complete
10-01 23:23:24 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_ba_tools.get_student_birthday, lineno=31) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot_plugin_ba_tools/get_student_birthday/__init__.py", line 45, in _
    students: list[Student] = await get_students_by_birth_month(real_month)
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot_plugin_ba_tools/utils/common.py", line 78, in get_students_by_birth_month
    students: list[Student] = await StudentDataLoader(
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot_plugin_ba_tools/utils/dataloader.py", line 78, in load_students
    raise DataLoadError("Loaded data is not a dictionary")
nonebot_plugin_ba_tools.utils.dataloader.DataLoadError: Loaded data is not a dictionary

```

**Comment by hanasa2023** [comment]
上述问题将在下一版本修复（国庆后） ~~才不会告诉你出门电脑带了，电源适配器没带呢~~

**Comment by hanasa2023** [comment]
非常抱歉拖了一个多月，现在您可以尝试[0.3.4](https://pypi.org/project/nonebot-plugin-ba-tools/),看看问题是否解决

**Comment by hanasa2023** [comment]
issue就先关了，有问题再开

**Comment by Jerry-Z07** [comment]
已确认功能均恢复正常
